# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Metropolis sampler for random walks using Rcpp.
#' @description A Metropolis sampler for random walks using Rcpp(in homework 9).
#' @param sigma variance of the proposal distribution (double)
#' @param x0 the initial position (double)
#' @param N the length of chain (integer)
#' @return a list consists of a generated chain and accept rate of the sampler
#' @examples
#' \dontrun{
#' N = 2000
#' sigma = c(.05, .5, 2, 16)
#' x0 = 25
#' rw1.c = MetropolisCpp(sigma[1],x0,N)
#' rw2.c = MetropolisCpp(sigma[2],x0,N)
#' rw3.c = MetropolisCpp(sigma[3],x0,N)
#' rw4.c = MetropolisCpp(sigma[4],x0,N)
#' #number of candidate points rejected
#' Rej = cbind(rw1.c$k, rw2.c$k, rw3.c$k, rw4.c$k)
#' Acc = round((N-Rej)/N,4)
#' rownames(Acc) = "Accept rates"
#' colnames(Acc) = paste("sigma",sigma)
#' Acc
#' }
#' @export
MetropolisCpp <- function(sigma, x0, N) {
    .Call('_StatComp_MetropolisCpp', PACKAGE = 'StatComp', sigma, x0, N)
}

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param N the number of samples
#' @param thin the number of between-sample random numbers
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' rnC <- gibbsC(100,10)
#' par(mfrow=c(2,1));
#' plot(rnC[,1],type='l')
#' plot(rnC[,2],type='l')
#' }
#' @export
gibbsC <- function(N, thin) {
    .Call('_StatComp_gibbsC', PACKAGE = 'StatComp', N, thin)
}

#' @title Use three inputs to predict response using Rcpp.
#' @description The prediction model is described in http://www.babelgraph.org/wp/?p=358.
#' @param age the first predictor (numeric)
#' @param female the second predictor (logical)
#' @param ily the third predictor (logical)
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' data(data)
#' attach(data)
#' res <- vaccC(age,female,ily)
#' }
#' @export
vaccC <- function(age, female, ily) {
    .Call('_StatComp_vaccC', PACKAGE = 'StatComp', age, female, ily)
}

